README.md, defaults/main.yml, tasks/database.yml, tasks/main.yml
I abandoned last pull request and use this one instead.
This pull request will add tasks to initial mysql database backend. It read initial mysql schema file from the package depends on os repo or powerdns repo but I not sure and don't think that it will work on RedHat family OS since I don't have CentOS to check path and test this. Also I add task to check database if it empty or not so it can rerun safety without harming current running database.
=>  Add tasks to initial mysql database backend

tasks/main.yml, vars/RedHat.yml
Adds precedence based var file loading and uses it to load RedHat specific var file to fix config dir.
The rpecedence based loading should generally be useful for creating distro/branch specific variable files to override defaults
=> Adds precedence based var loading, fixes RedHat config dir

tasks/database-sqlite3.yml
Currently the role is broken/fails even if you don't do defines for sqlite3.  From other pull requests it looks like you're deferring some additional changes for sqlite3, but this is a minimal update that makes things work again.
fix typo with `pdns_backends_gsqlite3_databases` -> `pdns_backends_sqlite3_databases` (no g).  You'd think this condition isn't hit if you don't define sqlite3 stuff since inclusion of this file appears to be blocked from tasks/main.yml using the "when" conditional, but ansible actually just adds those when conditions to the tasks within the included file and still executes them.
Simply correcting the typo isn't enough though since the "when" conditions apply to each item from "with_items".  This means that "with_items" is effectively parsed prior to the when …
=> Fix: role currently broke by sqlite3 updates

tasks/inspect-Debian.yml, vars/main.yml
Repository priority doesn't work on Ubuntu (Xenial)
Following Ubuntu installation guide at https://repo.powerdns.com/#ubuntu **Pin** should be set to repo site: **repo.powerdns.com**
> And this to '/etc/apt/preferences.d/pdns':
> 
> ```
> Package: pdns-*
> Pin: origin repo.powerdns.com
> Pin-Priority: 600`
> ```
=> Fix Ubuntu Pin: origin repo.powerdns.com

defaults/main.yml, tasks/configure.yml, tasks/database-mysql.yml, tasks/database-sqlite3.yml, tasks/inspect-Debian.yml, tasks/inspect-RedHat.yml, tasks/main.yml
The PR back-ports the changes already done on the recursor to support the installation of custom Auth versions.
=> Install a specific Auth version

tasks/main.yml, templates/pdns.conf.j2
Sort the config keys so position changes in the yaml dict will not trigger a rewrite.
Also run some tasks when actually invoking ansible-playbook with the -t option (so some things don't fail).
=> Sort config and run some tasks when needed

tasks/configure.yml, tasks/database-sqlite3.yml, tasks/repo-Debian.yml
To prevent leaking database passwords (in the case of the config) or DNSSEC cryptokeys (in the case of the sqlite database).
=> Make permissions stricter

.flake8, CHANGELOG.md, README.md, defaults/main.yml, tasks/database-mysql.yml, tasks/database-sqlite3.yml, tasks/inspect.yml, tasks/install.yml, tasks/repo-Debian.yml
Improved role documentation.
Adding a CHANGELOG.md file including all the major changes since the first release of the role.
=> Improved role documentation

CHANGELOG.md, README.md, defaults/main.yml, handlers/main.yml, meta/main.yml, molecule/pdns-41/molecule.yml, molecule/pdns-master/molecule.yml, molecule/resources/prepare.yml, molecule/resources/tests/all/test_common.py, molecule/resources/vars/pdns-common.yml, tasks/configure.yml, templates/override-service.systemd.conf.j2
This PR 
- implements a new option to configure systemd overrides (e.g. to enable coredumps).
- extends the test suite to Bionic
- fix some minor files permissions issues
=> Allow to manage systemd overrides

.travis.yml, test-requirements.txt, tox.ini
Adding Ansible 2.6 and 2.7 to validate role. Ansible 2.8 is still out of scope as it breaks the used Molecule version (2.14). Molecule 2.20+ is required for this, but also more updates changes to the current setup.
=> Newer ansible versions

tasks/database-mysql.yml, tasks/install.yml, tasks/main.yml, tasks/repo-RedHat.yml
While discovering the CI-part of this role I applied some easy fixes to make Ansible less noisy during deployment and let Ansible Lint generate less findings.
=> Fixing multiple Ansible Lint findings

templates/pdns.conf.j2
sameas() in jinja2 is more narrow, preventing "truthy" and "falsy" values from being misinterpreted.
Check for None already exists in backend section and should be in the base config loop as well.
=> Stop interpreting 0, 1, and null as no, yes, and None

.gitignore, .travis.yml, README.md, meta/main.yml, molecule/pdns-42/molecule.yml, molecule/pdns-42/playbook.yml, molecule/pdns-master/molecule.yml, molecule/resources/Dockerfile.centos-systemd.j2, molecule/resources/host_vars/centos-8.yml, molecule/resources/tests/all/test_common.py, molecule/resources/tests/backend-mysql/test_backend_mysql.py, molecule/resources/tests/backend-sqlite/test_backend_sqlite.py, molecule/resources/tests/repo-42/test_repo_42.py, molecule/resources/tests/repo-master/test_repo_master.py, molecule/resources/vars/pdns-repo-41.yml, molecule/resources/vars/pdns-repo-42.yml, tasks/configure.yml, tasks/database-mysql.yml, tasks/database-sqlite3.yml, tasks/inspect.yml, test-requirements.txt, tox.ini, vars/main.yml
This PR
- adds support to the Auth 4.3.x
- updates the CI to test against the Auth  4.2.x
- addresses some concerns with the config directories permissions raised in https://github.com/PowerDNS/pdns-ansible/pull/57 and https://github.com/PowerDNS/pdns-ansible/pull/65
- installs SQLite3 as reported in https://github.com/PowerDNS/pdns-ansible/issues/64
- updates the CI to test against Ansible 2.7, 2.8. and 2.9
- incorporates the feedback from https://github.com/PowerDNS/pdns-ansible/issues/58
=> Add support to the Auth 4.3 and fix some SQLite and permissions issues

tasks/database-mysql.yml
**FIXED**:
_mysql schema path for debian 10 as support for dbconfig was dropped in pdns = 4.1.3-4 on 31 Jul 2018_
resulting in a error at
_TASK [pdns : Import the PowerDNS MySQL schema]_
with
_"msg": "target /usr/share/dbconfig-common/data/pdns-backend-mysql/install/mysql does not exist on the host"_
=> FIXED: mysql schema path for debian 10

tasks/repo-Debian.yml
Allow using a apt_key from the ansible hosts instead of fetching it from a url
=> allow adding apt_key's from a file on the ansible server

defaults/main.yml, tasks/configure.yml, tasks/database-sqlite3.yml, vars/main.yml
In PowerDNS 4.3+, the service is started as the pdns user by default.
=> Ensure the file ownership and overrides are correct for 4.3+

README.md
This commit updates the documentation to mention the minimum Ansible
version required is 2.7
Fixes: #88
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>
=> doc: update ansible requirement

tasks/configure.yml
There's a way to achieve this operation without using `command`
module, let's use `systemd` module instead.
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>
=> configure: refact systemctl daemon-reload task

CHANGELOG.md, README.md, defaults/main.yml, tasks/database-lmdb.yml, tasks/main.yml
Management of directory and files for LMDB database.
=> lmdb: add lmdb management

tasks/database-sqlite3.yml
Sqlite schema files are located under /usr/share/doc/pdns/ (checked with pdns 4.4.0).
=> Fixed the schema.sqlite3.sql path on RedHat 8

.github/workflows/main.yml, molecule/pdns-master/molecule.yml, molecule/pdns-os-repos/converge.yml, molecule/resources/vars/pdns-common.yml, molecule/resources/vars/pdns-no-overrides.yml, molecule/resources/vars/pdns-os-repos.yml
Update molecules:
- Replace deprecated attribute `master` with `primary` as the former is no longer supported in master. Keep old attributes for test `pdns-no-repos` as it installs a very old version of `pdns`.
- Replace Ubuntu Bionic with Ubuntu Focal for `pdns-master`
Added tag to continue the tests even if one of the combinations fails.
=> Update pdns-master: replace deprecated attributes and replace bionic with focal

.github/workflows/main.yml, README.md, molecule/pdns-49/converge.yml, molecule/pdns-49/molecule.yml, molecule/pdns-os-repos/molecule.yml, molecule/resources/tests/repo-49/test_repo_49 .py, molecule/resources/vars/pdns-no-overrides.yml, molecule/resources/vars/pdns-os-repos.yml, molecule/resources/vars/pdns-repo-49.yml, vars/main.yml
Adding repository and CI for Auth49
=> Added Auth49

.github/workflows/main.yml, molecule/pdns-os-repos/molecule.yml, molecule/resources/Dockerfile.debian-systemd.j2, molecule/resources/host_vars/debian-10.yml, molecule/resources/host_vars/debian-11.yml, molecule/resources/host_vars/ubuntu-2004.yml, molecule/resources/vars/pdns-os-repos.yml, vars/Debian.yml
Some of the OSs used for the test `pdns-os-repos`, install older versions of Auth that use legacy terms/attributes no longer supported in recent versions.
This PR is an attempt to keep running the test for OSs that are still under support but that install EOL versions of Auth by default alongside the ones that install newer versions.
Of course, it is always simpler to just remove from the test OSs that install no supported versions of Auth and just close this PR.
=> Fix test pdns-os-repos

molecule/pdns-47/molecule.yml, molecule/pdns-48/molecule.yml, molecule/pdns-49/molecule.yml, molecule/pdns-master/molecule.yml, molecule/resources/create.yml, molecule/resources/tests/backend-mysql/test_backend_mysql.py, molecule/resources/tests/repo-master/test_repo_master.py, molecule/systemd-no-overrides/molecule.yml, tasks/database-mysql.yml, tasks/inspect.yml, test-requirements.txt, vars/Archlinux.yml
Included in this PR are fixes for:
- Version of `docker-py` set to 7.1.0. Older versions require a specific version of `requests` to work (see [here](https://github.com/docker/docker-py/issues/3256)
- Move from tests from`centos:7` to `oraclelinux:7`
- Adapt tests to comply with newer versions of auth that show a different string for `pdns_server --version` and also through stdout instead of stderr.
- Skip SSL validation for the `mysql` client in `archlinux`
- Mount `/sys/fs/cgroups` as `rw` to overcome the error that made containers fail after starting: `Failed to create /actions_job/b23bdd0759a907717ae61975e6bf5b5044ae8f9dee961e93a4c108e30868f395/init.scope control group: Read-only file system`
=> GH Actions: fix issues with CI

meta/main.yml, molecule/pdns-47/molecule.yml, molecule/pdns-48/molecule.yml, molecule/pdns-49/molecule.yml, molecule/pdns-master/molecule.yml, molecule/pdns-os-repos/molecule.yml, molecule/systemd-no-overrides/molecule.yml
Fixes errors in CI.
Platforms removed:
- `oraclelinux-7`
- `debian-10`
Added:
- `debian-11`
- `debian-12`
- `ubuntu-24.04`
=> Removed EOL targets RHEL-7 and Debian-10. Added Debian 11 and 12 and Ubuntu-24

.ansible-lint, .github/workflows/main.yml, molecule/pdns-47/converge.yml, molecule/pdns-47/molecule.yml, molecule/pdns-48/converge.yml, molecule/pdns-48/molecule.yml, molecule/pdns-49/converge.yml, molecule/pdns-49/molecule.yml, molecule/pdns-master/converge.yml, molecule/pdns-master/molecule.yml, molecule/pdns-os-repos/converge.yml, molecule/pdns-os-repos/molecule.yml, molecule/resources/create.yml, molecule/resources/destroy.yml, molecule/resources/prepare.yml, molecule/resources/vars/molecule.yml, molecule/systemd-no-overrides/converge.yml, molecule/systemd-no-overrides/molecule.yml, tasks/configure.yml, tasks/database-lmdb.yml, tasks/database-mysql.yml, tasks/database-sqlite3.yml, tasks/inspect.yml, tasks/install.yml, tasks/main.yml, tasks/repo-Debian.yml, tasks/repo-RedHat.yml, tasks/selinux.yml, test-requirements.txt, tox.ini
Tests now run against `ansible-core 2.14, 2.15 and 2.16`.
Added linter to CI workflow and fixed some lint issues
=> CI tests: upgraded version of molecule and ansible-core packages

molecule/pdns-47/molecule.yml, molecule/pdns-48/molecule.yml, molecule/pdns-49/molecule.yml, molecule/pdns-master/molecule.yml, molecule/pdns-os-repos/molecule.yml, molecule/systemd-no-overrides/molecule.yml
This PR removes Ubuntu 20.04 from the molecule tests. 
Packages from master are no longer built, which makes the [CI tests fail](https://github.com/PowerDNS/pdns-ansible/actions/runs/16701691361/job/47313504275#step:5:672)
In addition, CI tests occasionally fail when granting permissions in MySQL ([example](https://github.com/PowerDNS/pdns-ansible/actions/runs/16701691361/job/47313504252#step:5:541)). This PR sets the number of concurrent processes running tasks to `1`, increasing the duration of the workflow by ~3 minutes. This WO mitigates this behaviour.
=> GH Actions: remove EOL Ubuntu 20.04 from molecule tests
